<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit824dc051590f15d2c901eccb8caae400
{
    public static $prefixLengthsPsr4 = array (
        'A' => 
        array (
            'Agx14\\RiyadhMetro\\' => 18,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Agx14\\RiyadhMetro\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit824dc051590f15d2c901eccb8caae400::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit824dc051590f15d2c901eccb8caae400::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit824dc051590f15d2c901eccb8caae400::$classMap;

        }, null, ClassLoader::class);
    }
}
